package:
  name: "unimodel"
  version: "0.2.6"

source:
  branch: main
  git_url: https://github.com/meteocat/unimodel.git

requirements:
  build:
    - python
    - setuptools_scm
    - cfgrib
    - dask
    - eccodes
    - netcdf4
    - numba
    - numpy >=1.24
    - pyshp
    - rioxarray
    - scikit-learn
    - shapely
    - xarray

  run:
    - python
    - cfgrib
    - dask
    - eccodes
    - netcdf4
    - numba
    - numpy >=1.24
    - pyshp
    - rioxarray
    - scikit-learn
    - shapely
    - xarray

test:
  imports:
    - unimodel

about:
  home: https://github.com/meteocat/unimodel
  license: MIT
  license_family: MIT
  summary: Standarisation of meteorological model grids.